[build-system]
requires = ["setuptools>=61.0", "anndata>=0.13.0", "hdf5plugin>=7.0.0", "argparse", "numpy", "scipy", "pathlib", "importlib", "packaging"]
build-backend = "setuptools.build_meta"

[project]
name = "recode_h5ad"
version = "0.1.0"
authors = [
  { name="Gabriel Hoffman", email="gabriel.hoffman@gmail.com" },
]
description = "Recode H5AD file changing sparsity format and cell sorting"
readme = "README.md"
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
Homepage = "https://github.com"
